name: Daily Cron Job

on:
  schedule:
    - cron: '0 7 * * *' # Runs every day at 7 AM UTC

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run curl command
        run: |
          curl -X GET https://scrum-roulette.vercel.app/api/scrum-roulette
